// Generated by binpac_quickstart

#include "coap.h"

#include "Reporter.h"

#include "events.bif.h"

using namespace analyzer::Local_coap;

coap_Analyzer::coap_Analyzer(Connection* c)

: analyzer::Analyzer("coap", c)

	{
	interp = new binpac::coap::coap_Conn(this);
	
	}

coap_Analyzer::~coap_Analyzer()
	{
	delete interp;
	}

void coap_Analyzer::Done()
	{
	
	Analyzer::Done();
	
	}

void coap_Analyzer::DeliverPacket(int len, const u_char* data,
	 			  bool orig, uint64_t seq, const IP_Hdr* ip, int caplen)
	{
	Analyzer::DeliverPacket(len, data, orig, seq, ip, caplen);

	try
		{
		interp->NewData(orig, data, data + len);
		}
	catch ( const binpac::Exception& e )
		{
		ProtocolViolation(fmt("Binpac exception: %s", e.c_msg()));
		}
	}

