// Generated by binpac_quickstart

#include "Plugin.h"
#include "analyzer/Component.h"
#include "coap.h"

namespace plugin {
namespace Zeek_coap {
       
class Plugin : public plugin::Plugin {
public:
	plugin::Configuration :Configure()
	{
	AddComponent(new ::analyzer::Component("coap",
	             ::analyzer::coap::coap_analyzer::InstantiateAnalyzer));

	plugin::Configuration config;
	config.name = "Zeek::coap";
	config.description = "coap Protocol Analyzer";
	config.version.major = 0;
	config.version.minor = 1;
	config.version.patch = 0;
	return config;
	}
} plugin;

}
